---
- name: Update APT package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - software-properties-common
      - curl
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add GPG key for CRI-O
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key
    keyring: /etc/apt/keyrings/cri-o-apt-keyring.gpg
    state: present

- name: Add CRI-O APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/ /"
    state: present
    filename: cri-o

- name: Update APT package index again
  ansible.builtin.apt:
    update_cache: yes

- name: Install CRI-O
  ansible.builtin.apt:
    name: cri-o
    state: present

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start CRI-O service
  ansible.builtin.systemd:
    name: crio
    enabled: yes
    state: started
