---
- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: Add GPG key for Kubernetes APT repository
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key"
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /"
    state: present
    filename: kubernetes

- name: Update APT package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install Kubeadm, Kubelet, and Kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Install jq
  ansible.builtin.apt:
    name: jq
    state: present

- name: Set local IP variable
  set_fact:
    local_ip: "{{ inventory_hostname }}"
- name: "modprobe br_netfilter"
  ansible.builtin.command: modprobe br_netfilter
- name: "modprobe br_netfilter"
  ansible.builtin.command: sysctl -w net.ipv4.ip_forward=1

- name: Configure kubelet
  ansible.builtin.copy:
    dest: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS=--node-ip={{ local_ip }}
