---
- name: Setting UP K8s node (Master).
  hosts: vm
  become: true
  become_method: sudo
  become_user: root

  vars:
    pod_cidr: "10.10.0.0/16" # Change this to your desired CIDR
    kubernetes_version: "1.28"

  tasks:
    - name: "Setting up the Base"
      ansible.builtin.include_tasks:
        file: base.yml
